baseURL = "https://lakewood.urbanism-guide.com/"
title = "Lakewood Urbanism Guide"
theme = "hugo-book"

# Hugo settings
enableGitInfo = true
enableEmoji = false

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookRepo = "https://github.com/prestomation/lakewood-urbanism-guide"
  BookEditPath = "edit/main"
  BookDateFormat = "January 2, 2006"
  BookSection = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.before]]
    name = "Quick Start"
    url = "/quick-start/"
    weight = 1
  [[menu.before]]
    name = "Glossary"
    url = "/glossary/"
    weight = 2
  [[menu.before]]
    name = "Guides"
    url = "/guides/"
    weight = 3
  [[menu.before]]
    name = "Timeline"
    url = "/timeline/"
    weight = 4
  [[menu.before]]
    name = "Data"
    url = "/data/"
    weight = 5
  [[menu.before]]
    name = "Blog"
    url = "/blog/"
    weight = 6
