baseURL = "https://lakewood.urbanism-guide.com/"
title = "Lakewood Urbanism Guide"
theme = "hugo-book"

# Hugo settings
enableGitInfo = true
enableEmoji = false

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookRepo = "https://github.com/prestomation/lakewood-urbanism-guide"
  BookEditPath = "edit/main"
  BookDateFormat = "January 2, 2006"
  BookSection = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
